global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
      scheme: http
      tls_config:
        insecure_skip_verify: false

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'markzap-app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['markzap-app:3000']
        labels:
          app: 'markzap'
          env: 'production'
