import React, { useState, useEffect } from 'react';
import { SearchInputBox } from './SearchInputBox';
import { useAuth } from '../AuthContext';
import { saveChatToSupabase } from '../chatService';
import { generateMarkZapAIResponse } from '../aiEngine';

export const ChatView = ({ initialQuery }) => {
  const { user } = useAuth();
  
  const initialAIResponse = generateMarkZapAIResponse(initialQuery || '');

  const [messages, setMessages] = useState([
    {
      id: 1,
      sender: 'user',
      text: initialQuery
    },
    {
      id: 2,
      sender: 'ai',
      text: initialQuery ? initialAIResponse.text : '',
      leads: initialAIResponse.leads
    }
  ]);

  // Sync session to Supabase
  useEffect(() => {
    if (initialQuery && messages.length > 0) {
      saveChatToSupabase(user?.id, initialQuery, messages);
    }
  }, [messages, user, initialQuery]);

  const handleSendFollowUp = (queryText) => {
    if (!queryText.trim()) return;
    
    const aiResponse = generateMarkZapAIResponse(queryText);

    const userMsg = { id: Date.now(), sender: 'user', text: queryText };
    const aiMsg = {
      id: Date.now() + 1,
      sender: 'ai',
      text: aiResponse.text,
      leads: aiResponse.leads
    };
    setMessages((prev) => [...prev, userMsg, aiMsg]);
  };

  /**
   * PDF Download Generator Function — Formats all lead cards into a clean PDF print report
   */
  const handleDownloadPDF = (leadsList) => {
    if (!leadsList || leadsList.length === 0) return;

    const printWin = window.open('', '_blank');
    if (!printWin) {
      alert("Please allow popups to download your PDF lead report.");
      return;
    }

    const reportHtml = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>Mark Zap Agent-Reach Lead Intelligence Report</title>
        <style>
          body {
            font-family: 'Helvetica Neue', Arial, sans-serif;
            color: #1a1a1a;
            padding: 30px;
            margin: 0;
            line-height: 1.5;
          }
          .header {
            border-bottom: 2px solid #30D158;
            padding-bottom: 16px;
            margin-bottom: 24px;
            display: flex;
            justify-content: space-between;
            align-items: center;
          }
          .title {
            font-size: 24px;
            font-weight: 800;
            color: #000000;
            margin: 0;
          }
          .subtitle {
            font-size: 13px;
            color: #666666;
            margin-top: 4px;
          }
          .badge {
            background-color: #e6f9ed;
            color: #1e8e3e;
            padding: 6px 14px;
            border-radius: 6px;
            font-weight: bold;
            font-size: 12px;
          }
          .lead-card {
            border: 1px solid #e0e0e0;
            border-radius: 10px;
            padding: 16px;
            margin-bottom: 16px;
            page-break-inside: avoid;
            background-color: #fafafa;
          }
          .lead-title {
            font-size: 18px;
            font-weight: 700;
            color: #111111;
            margin-bottom: 4px;
          }
          .lead-meta {
            font-size: 13px;
            color: #555555;
            margin-bottom: 10px;
          }
          .meta-grid {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 8px;
            font-size: 13px;
            background-color: #ffffff;
            padding: 10px;
            border-radius: 6px;
            border: 1px solid #eeeeee;
            margin-bottom: 10px;
          }
          .why-box {
            background-color: #f0fdf4;
            border: 1px solid #bbf7d0;
            border-radius: 6px;
            padding: 10px 12px;
            font-size: 12.5px;
            color: #166534;
          }
          .footer {
            margin-top: 40px;
            padding-top: 16px;
            border-top: 1px solid #dddddd;
            font-size: 11px;
            color: #888888;
            text-align: center;
          }
          @media print {
            body { padding: 0; }
            .no-print { display: none; }
          }
        </style>
      </head>
      <body>
        <div class="header">
          <div>
            <h1 class="title">Mark Zap Lead Intelligence Report</h1>
            <div class="subtitle">Generated by Agent-Reach Engine • Project ID: projects/171579689146</div>
          </div>
          <div class="badge">Target: Businesses Without Websites</div>
        </div>

        <div style="margin-bottom: 20px; font-size: 14px; font-weight: 600;">
          Discovered Leads Count: ${leadsList.length} Prospect Companies
        </div>

        ${leadsList.map((lead, idx) => `
          <div class="lead-card">
            <div class="lead-title">${idx + 1}. ${lead.name}</div>
            <div class="lead-meta">${lead.type} • ${lead.location}</div>
            <div class="meta-grid">
              <div><strong>Status:</strong> ${lead.websiteStatus}</div>
              <div><strong>Est. Revenue:</strong> ${lead.revenueEstimate}</div>
              <div><strong>Phone:</strong> ${lead.phone}</div>
              <div><strong>Email:</strong> ${lead.email}</div>
              <div><strong>Rating:</strong> ${lead.rating}</div>
              <div><strong>Google Maps Link:</strong> ${lead.gmapsUrl}</div>
            </div>
            <div class="why-box">
              <strong>💡 Why They Will Build From Us:</strong> ${lead.whyBuildFromUs}
            </div>
          </div>
        `).join('')}

        <div class="footer">
          Mark Zap Lead Finder • Fast. Smart. Digital. • Confidential Lead Export Report
        </div>

        <script>
          window.onload = function() {
            window.print();
          };
        </script>
      </body>
      </html>
    `;

    printWin.document.write(reportHtml);
    printWin.document.close();
  };

  return (
    <div 
      style={{
        position: 'relative',
        zIndex: 20,
        width: '100%',
        maxWidth: '860px',
        margin: '0 auto',
        padding: '60px 20px 140px 20px',
        boxSizing: 'border-box',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        color: '#ffffff',
        fontFamily: "'Schibsted Grotesk', 'Inter', sans-serif"
      }}
    >
      {/* Messages Conversation Stream */}
      <div 
        style={{
          width: '100%',
          display: 'flex',
          flexDirection: 'column',
          gap: '24px'
        }}
      >
        {messages.map((msg) => {
          if (!msg.text) return null;

          if (msg.sender === 'user') {
            return (
              <div 
                key={msg.id}
                style={{
                  display: 'flex',
                  flexDirection: 'column',
                  alignItems: 'flex-end',
                  width: '100%'
                }}
              >
                {/* User Sender Label */}
                <div 
                  style={{
                    fontSize: '12px',
                    fontWeight: 600,
                    color: 'rgba(255, 255, 255, 0.55)',
                    marginBottom: '6px',
                    paddingRight: '4px'
                  }}
                >
                  You
                </div>

                {/* User Message inside a sleek white card box */}
                <div 
                  style={{
                    maxWidth: '85%',
                    padding: '16px 22px',
                    borderRadius: '18px 18px 4px 18px',
                    backgroundColor: 'rgba(255, 255, 255, 0.95)',
                    color: '#000000',
                    boxShadow: '0 10px 30px rgba(0, 0, 0, 0.25)',
                    fontSize: '16px',
                    lineHeight: '1.5',
                    fontWeight: 400
                  }}
                >
                  <p style={{ margin: 0 }}>{msg.text}</p>
                </div>
              </div>
            );
          }

          /* AI Response: Dynamic Mark Zap AI Agent-Reach Output */
          return (
            <div 
              key={msg.id}
              style={{
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'flex-start',
                width: '100%',
                marginTop: '4px'
              }}
            >
              {/* AI Sender Label & PDF Download Button */}
              <div 
                style={{
                  width: '100%',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'space-between',
                  marginBottom: '8px',
                  paddingLeft: '4px',
                  paddingRight: '4px'
                }}
              >
                <div style={{ fontSize: '12px', fontWeight: 600, color: 'rgba(255, 255, 255, 0.55)' }}>
                  Mark Zap Agent-Reach AI Engine
                </div>

                {msg.leads && msg.leads.length > 0 && (
                  <button
                    onClick={() => handleDownloadPDF(msg.leads)}
                    style={{
                      backgroundColor: 'rgba(48, 209, 88, 0.15)',
                      color: '#30D158',
                      border: '1px solid rgba(48, 209, 88, 0.35)',
                      borderRadius: '8px',
                      padding: '5px 12px',
                      fontSize: '12px',
                      fontWeight: 600,
                      cursor: 'pointer',
                      display: 'flex',
                      alignItems: 'center',
                      gap: '6px',
                      transition: 'transform 0.15s ease'
                    }}
                  >
                    <span>📄 Download All Leads as PDF</span>
                  </button>
                )}
              </div>

              {/* AI Response Text */}
              <div 
                style={{
                  width: '100%',
                  color: '#ffffff',
                  fontSize: '15px',
                  lineHeight: '1.6',
                  fontWeight: 400,
                  paddingLeft: '4px',
                  whiteSpace: 'pre-wrap'
                }}
              >
                {msg.text}
              </div>

              {/* Agent-Reach Interactive Prospect Lead Cards */}
              {msg.leads && msg.leads.length > 0 && (
                <div style={{ width: '100%', display: 'flex', flexDirection: 'column', gap: '14px', marginTop: '16px' }}>
                  {msg.leads.map((lead, lIdx) => (
                    <div
                      key={lIdx}
                      style={{
                        backgroundColor: 'rgba(14, 18, 16, 0.95)',
                        border: '1px solid rgba(255, 255, 255, 0.14)',
                        borderRadius: '16px',
                        padding: '18px 20px',
                        display: 'flex',
                        flexDirection: 'column',
                        gap: '10px',
                        boxShadow: '0 10px 30px rgba(0, 0, 0, 0.4)'
                      }}
                    >
                      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                        <div>
                          <div style={{ fontSize: '17px', fontWeight: 700, color: '#ffffff' }}>{lead.name}</div>
                          <div style={{ fontSize: '12.5px', color: 'rgba(255, 255, 255, 0.6)', marginTop: '2px' }}>
                            {lead.type} • {lead.location}
                          </div>
                        </div>
                        <span style={{ fontSize: '11.5px', fontWeight: 700, color: '#ff453a', backgroundColor: 'rgba(255, 69, 58, 0.15)', padding: '4px 10px', borderRadius: '8px' }}>
                          {lead.websiteStatus}
                        </span>
                      </div>

                      <div style={{ display: 'flex', flexWrap: 'wrap', gap: '16px', fontSize: '13px', color: 'rgba(255, 255, 255, 0.85)', paddingTop: '4px', borderTop: '1px solid rgba(255,255,255,0.06)' }}>
                        <div><strong>Est. Revenue:</strong> <span style={{ color: '#30D158' }}>{lead.revenueEstimate}</span></div>
                        <div><strong>Phone:</strong> <a href={`tel:${lead.phone}`} style={{ color: '#30D158', textDecoration: 'none' }}>{lead.phone}</a></div>
                        <div><strong>Email:</strong> <a href={`mailto:${lead.email}`} style={{ color: '#0A84FF', textDecoration: 'none' }}>{lead.email}</a></div>
                        <div><strong>Rating:</strong> {lead.rating}</div>
                      </div>

                      <div style={{ fontSize: '12.5px', color: 'rgba(255, 255, 255, 0.65)' }}>
                        <strong>Social Profiles:</strong> {lead.social}
                      </div>

                      {/* Why They Will Build From Us Callout Box */}
                      {lead.whyBuildFromUs && (
                        <div
                          style={{
                            backgroundColor: 'rgba(48, 209, 88, 0.10)',
                            border: '1px solid rgba(48, 209, 88, 0.25)',
                            borderRadius: '10px',
                            padding: '10px 14px',
                            fontSize: '12.5px',
                            color: '#ffffff',
                            lineHeight: '1.45'
                          }}
                        >
                          <strong style={{ color: '#30D158' }}>💡 Why They Will Build From Us:</strong> {lead.whyBuildFromUs}
                        </div>
                      )}

                      <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginTop: '4px' }}>
                        <a
                          href={lead.gmapsUrl}
                          target="_blank"
                          rel="noopener noreferrer"
                          style={{
                            backgroundColor: 'rgba(10, 132, 255, 0.18)',
                            color: '#0A84FF',
                            border: '1px solid rgba(10, 132, 255, 0.3)',
                            borderRadius: '8px',
                            padding: '6px 14px',
                            fontSize: '12.5px',
                            fontWeight: 600,
                            textDecoration: 'none',
                            display: 'inline-flex',
                            alignItems: 'center',
                            gap: '6px'
                          }}
                        >
                          📍 Open in Google Maps
                        </a>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          );
        })}
      </div>

      {/* Docked Bottom Typing Bar */}
      <div 
        style={{
          position: 'fixed',
          bottom: '24px',
          left: '50%',
          transform: 'translateX(-50%)',
          width: 'calc(100% - 32px)',
          maxWidth: '728px',
          zIndex: 50,
          transition: 'transform 0.3s cubic-bezier(0.16, 1, 0.3, 1)'
        }}
      >
        <SearchInputBox 
          onSubmit={handleSendFollowUp} 
          placeholder="Search mid-range businesses without a website..." 
        />
      </div>
    </div>
  );
};
