import React, { useState, useEffect } from 'react';
import { SearchInputBox } from './SearchInputBox';
import { useAuth } from '../AuthContext';
import { saveChatToSupabase } from '../chatService';
import { generateMarkZapAIResponse } from '../aiEngine';

export const ChatView = ({ initialQuery }) => {
  const { user } = useAuth();
  
  const initialAIResponse = generateMarkZapAIResponse(initialQuery || '');

  const [messages, setMessages] = useState([
    {
      id: 1,
      sender: 'user',
      text: initialQuery
    },
    {
      id: 2,
      sender: 'ai',
      text: initialQuery ? initialAIResponse.text : '',
      leads: initialAIResponse.leads
    }
  ]);

  const [approvedLeads, setApprovedLeads] = useState({});
  const [selectedProposalLead, setSelectedProposalLead] = useState(null);

  // Sync session to Supabase
  useEffect(() => {
    if (initialQuery && messages.length > 0) {
      saveChatToSupabase(user?.id, initialQuery, messages);
    }
  }, [messages, user, initialQuery]);

  const handleSendFollowUp = (queryText) => {
    if (!queryText.trim()) return;
    
    const aiResponse = generateMarkZapAIResponse(queryText);

    const userMsg = { id: Date.now(), sender: 'user', text: queryText };
    const aiMsg = {
      id: Date.now() + 1,
      sender: 'ai',
      text: aiResponse.text,
      leads: aiResponse.leads
    };
    setMessages((prev) => [...prev, userMsg, aiMsg]);
  };

  const handleApproveLead = (lead) => {
    setApprovedLeads((prev) => ({ ...prev, [lead.name]: true }));
    setSelectedProposalLead(lead);
  };

  const handleDownloadPDF = (leadsList) => {
    if (!leadsList || leadsList.length === 0) return;

    const printWin = window.open('', '_blank');
    if (!printWin) {
      alert("Please allow popups to download your PDF lead report.");
      return;
    }

    const reportHtml = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>Mark Zap Agent-Reach Lead Intelligence Report</title>
        <style>
          body { font-family: 'Helvetica Neue', Arial, sans-serif; color: #1a1a1a; padding: 30px; line-height: 1.5; }
          .header { border-bottom: 2px solid #30D158; padding-bottom: 16px; margin-bottom: 24px; display: flex; justify-content: space-between; }
          .title { font-size: 24px; font-weight: 800; margin: 0; }
          .badge { background-color: #e6f9ed; color: #1e8e3e; padding: 6px 14px; border-radius: 6px; font-weight: bold; font-size: 12px; }
          .lead-card { border: 1px solid #e0e0e0; border-radius: 10px; padding: 16px; margin-bottom: 16px; background-color: #fafafa; }
          .meta-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 8px; font-size: 13px; background-color: #ffffff; padding: 10px; border-radius: 6px; margin-bottom: 10px; }
          .why-box { background-color: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 6px; padding: 10px 12px; font-size: 12.5px; color: #166534; }
        </style>
      </head>
      <body>
        <div class="header">
          <div>
            <h1 class="title">Mark Zap Lead Intelligence Report</h1>
            <div style="font-size:13px; color:#666;">Generated by Agent-Reach Engine (Scanned 20 Leads ➔ Filtered Top ${leadsList.length})</div>
          </div>
          <div class="badge">Target: Businesses Without Websites</div>
        </div>

        ${leadsList.map((lead, idx) => `
          <div class="lead-card">
            <div style="font-size:18px; font-weight:700;">${idx + 1}. ${lead.name}</div>
            <div style="font-size:13px; color:#555; margin-bottom:10px;">${lead.type} • ${lead.location}</div>
            <div class="meta-grid">
              <div><strong>Status:</strong> ${lead.websiteStatus}</div>
              <div><strong>Est. Revenue:</strong> ${lead.revenueEstimate}</div>
              <div><strong>Phone:</strong> ${lead.phone}</div>
              <div><strong>Email:</strong> ${lead.email}</div>
              <div><strong>Rating:</strong> ${lead.rating}</div>
              <div><strong>Google Maps:</strong> ${lead.gmapsUrl}</div>
            </div>
            <div class="why-box">
              <strong>💡 Why They Will Build From Us:</strong> ${lead.whyBuildFromUs}
            </div>
          </div>
        `).join('')}

        <script>window.onload = function() { window.print(); };</script>
      </body>
      </html>
    `;

    printWin.document.write(reportHtml);
    printWin.document.close();
  };

  return (
    <div 
      style={{
        position: 'relative',
        zIndex: 20,
        width: '100%',
        maxWidth: '860px',
        margin: '0 auto',
        padding: '60px 20px 140px 20px',
        boxSizing: 'border-box',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        color: '#ffffff',
        fontFamily: "'Schibsted Grotesk', 'Inter', sans-serif"
      }}
    >
      {/* Messages Conversation Stream */}
      <div 
        style={{
          width: '100%',
          display: 'flex',
          flexDirection: 'column',
          gap: '24px'
        }}
      >
        {messages.map((msg) => {
          if (!msg.text) return null;

          if (msg.sender === 'user') {
            return (
              <div 
                key={msg.id}
                style={{
                  display: 'flex',
                  flexDirection: 'column',
                  alignItems: 'flex-end',
                  width: '100%'
                }}
              >
                <div 
                  style={{
                    fontSize: '12px',
                    fontWeight: 600,
                    color: 'rgba(255, 255, 255, 0.55)',
                    marginBottom: '6px',
                    paddingRight: '4px'
                  }}
                >
                  You
                </div>

                <div 
                  style={{
                    maxWidth: '85%',
                    padding: '16px 22px',
                    borderRadius: '18px 18px 4px 18px',
                    backgroundColor: 'rgba(255, 255, 255, 0.95)',
                    color: '#000000',
                    boxShadow: '0 10px 30px rgba(0, 0, 0, 0.25)',
                    fontSize: '16px',
                    lineHeight: '1.5',
                    fontWeight: 400
                  }}
                >
                  <p style={{ margin: 0 }}>{msg.text}</p>
                </div>
              </div>
            );
          }

          /* AI Response */
          return (
            <div 
              key={msg.id}
              style={{
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'flex-start',
                width: '100%',
                marginTop: '4px'
              }}
            >
              {/* AI Sender Label & PDF Download Button */}
              <div 
                style={{
                  width: '100%',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'space-between',
                  marginBottom: '8px',
                  paddingLeft: '4px',
                  paddingRight: '4px'
                }}
              >
                <div style={{ fontSize: '12px', fontWeight: 600, color: 'rgba(255, 255, 255, 0.55)' }}>
                  Mark Zap Agent-Reach AI Engine
                </div>

                {msg.leads && msg.leads.length > 0 && (
                  <button
                    onClick={() => handleDownloadPDF(msg.leads)}
                    style={{
                      backgroundColor: 'rgba(48, 209, 88, 0.15)',
                      color: '#30D158',
                      border: '1px solid rgba(48, 209, 88, 0.35)',
                      borderRadius: '8px',
                      padding: '5px 12px',
                      fontSize: '12px',
                      fontWeight: 600,
                      cursor: 'pointer',
                      display: 'flex',
                      alignItems: 'center',
                      gap: '6px'
                    }}
                  >
                    <span>📄 Download All Leads as PDF</span>
                  </button>
                )}
              </div>

              {/* AI Response Text */}
              <div 
                style={{
                  width: '100%',
                  color: '#ffffff',
                  fontSize: '15px',
                  lineHeight: '1.6',
                  fontWeight: 400,
                  paddingLeft: '4px',
                  whiteSpace: 'pre-wrap'
                }}
              >
                {msg.text}
              </div>

              {/* Agent-Reach Interactive Prospect Lead Cards */}
              {msg.leads && msg.leads.length > 0 && (
                <div style={{ width: '100%', display: 'flex', flexDirection: 'column', gap: '14px', marginTop: '16px' }}>
                  {msg.leads.map((lead, lIdx) => {
                    const isApproved = approvedLeads[lead.name];

                    return (
                      <div
                        key={lIdx}
                        style={{
                          backgroundColor: 'rgba(14, 18, 16, 0.95)',
                          border: isApproved ? '1px solid #30D158' : '1px solid rgba(255, 255, 255, 0.14)',
                          borderRadius: '16px',
                          padding: '18px 20px',
                          display: 'flex',
                          flexDirection: 'column',
                          gap: '10px',
                          boxShadow: '0 10px 30px rgba(0, 0, 0, 0.4)',
                          position: 'relative'
                        }}
                      >
                        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                          <div>
                            <div style={{ fontSize: '17px', fontWeight: 700, color: '#ffffff' }}>{lead.name}</div>
                            <div style={{ fontSize: '12.5px', color: 'rgba(255, 255, 255, 0.6)', marginTop: '2px' }}>
                              {lead.type} • {lead.location}
                            </div>
                          </div>
                          <span style={{ fontSize: '11.5px', fontWeight: 700, color: '#ff453a', backgroundColor: 'rgba(255, 69, 58, 0.15)', padding: '4px 10px', borderRadius: '8px' }}>
                            {lead.websiteStatus}
                          </span>
                        </div>

                        <div style={{ display: 'flex', flexWrap: 'wrap', gap: '16px', fontSize: '13px', color: 'rgba(255, 255, 255, 0.85)', paddingTop: '4px', borderTop: '1px solid rgba(255,255,255,0.06)' }}>
                          <div><strong>Est. Revenue:</strong> <span style={{ color: '#30D158' }}>{lead.revenueEstimate}</span></div>
                          <div><strong>Phone:</strong> <a href={`tel:${lead.phone}`} style={{ color: '#30D158', textDecoration: 'none' }}>{lead.phone}</a></div>
                          <div><strong>Email:</strong> <a href={`mailto:${lead.email}`} style={{ color: '#0A84FF', textDecoration: 'none' }}>{lead.email}</a></div>
                          <div><strong>Rating:</strong> {lead.rating}</div>
                        </div>

                        <div style={{ fontSize: '12.5px', color: 'rgba(255, 255, 255, 0.65)' }}>
                          <strong>Social Profiles:</strong> {lead.social}
                        </div>

                        {/* Why They Will Build From Us Callout Box */}
                        {lead.whyBuildFromUs && (
                          <div
                            style={{
                              backgroundColor: 'rgba(48, 209, 88, 0.10)',
                              border: '1px solid rgba(48, 209, 88, 0.25)',
                              borderRadius: '10px',
                              padding: '10px 14px',
                              fontSize: '12.5px',
                              color: '#ffffff',
                              lineHeight: '1.45'
                            }}
                          >
                            <strong style={{ color: '#30D158' }}>💡 Why They Will Build From Us:</strong> {lead.whyBuildFromUs}
                          </div>
                        )}

                        {/* Action Buttons: Open Maps & Approve Proposal */}
                        <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginTop: '4px' }}>
                          <a
                            href={lead.gmapsUrl}
                            target="_blank"
                            rel="noopener noreferrer"
                            style={{
                              backgroundColor: 'rgba(10, 132, 255, 0.18)',
                              color: '#0A84FF',
                              border: '1px solid rgba(10, 132, 255, 0.3)',
                              borderRadius: '8px',
                              padding: '6px 14px',
                              fontSize: '12.5px',
                              fontWeight: 600,
                              textDecoration: 'none',
                              display: 'inline-flex',
                              alignItems: 'center',
                              gap: '6px'
                            }}
                          >
                            📍 Open in Google Maps
                          </a>

                          <button
                            onClick={() => handleApproveLead(lead)}
                            style={{
                              backgroundColor: isApproved ? '#30D158' : 'rgba(48, 209, 88, 0.2)',
                              color: isApproved ? '#000000' : '#30D158',
                              border: '1px solid rgba(48, 209, 88, 0.4)',
                              borderRadius: '8px',
                              padding: '6px 14px',
                              fontSize: '12.5px',
                              fontWeight: 700,
                              cursor: 'pointer'
                            }}
                          >
                            {isApproved ? '✓ Approved — Proposal Ready' : '✅ Approve & Generate Proposal'}
                          </button>
                        </div>
                      </div>
                    );
                  })}
                </div>
              )}
            </div>
          );
        })}
      </div>

      {/* Modal Popup for Generated Proposal Email */}
      {selectedProposalLead && (
        <div
          style={{
            position: 'fixed',
            inset: 0,
            backgroundColor: 'rgba(0,0,0,0.85)',
            zIndex: 120,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            padding: '20px'
          }}
        >
          <div
            style={{
              width: '100%',
              maxWidth: '680px',
              backgroundColor: '#0c100e',
              border: '1px solid rgba(255, 255, 255, 0.16)',
              borderRadius: '24px',
              padding: '24px 28px',
              boxSizing: 'border-box',
              color: '#ffffff',
              boxShadow: '0 40px 100px rgba(0,0,0,0.9)'
            }}
          >
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
              <div style={{ fontSize: '18px', fontWeight: 700, color: '#30D158' }}>
                ✉️ Custom Sales Proposal & Cold Outreach Email
              </div>
              <button 
                onClick={() => setSelectedProposalLead(null)}
                style={{ background: 'none', border: 'none', color: '#fff', fontSize: '18px', cursor: 'pointer' }}
              >
                ✕
              </button>
            </div>

            <div style={{ fontSize: '13px', color: 'rgba(255,255,255,0.7)', marginBottom: '14px' }}>
              Target: <strong>{selectedProposalLead.name}</strong> ({selectedProposalLead.email})
            </div>

            <div
              style={{
                backgroundColor: '#070907',
                border: '1px solid rgba(255,255,255,0.1)',
                borderRadius: '12px',
                padding: '18px',
                fontSize: '13.5px',
                lineHeight: '1.6',
                fontFamily: 'monospace',
                whiteSpace: 'pre-wrap',
                color: '#d4d4d4'
              }}
            >
{`Subject: High-converting website proposal for ${selectedProposalLead.name}

Hi Team ${selectedProposalLead.name},

I came across ${selectedProposalLead.name} on Google Maps in ${selectedProposalLead.location}. You have an impressive reputation with ${selectedProposalLead.rating}, but I noticed you currently do not have a dedicated online booking website.

At Mark Zap, we build modern, high-speed websites for local businesses. Based on your location and lead volume, a custom website with online appointment booking can capture an estimated 30+ new customer bookings every week.

Would you be open to a 5-minute preview of a custom website design concept we prepared for ${selectedProposalLead.name}?

Best regards,
Mark Zap Digital Agency
Phone: ${selectedProposalLead.phone}`}
            </div>

            <div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: '18px', gap: '12px' }}>
              <button
                onClick={() => {
                  navigator.clipboard.writeText(`Subject: High-converting website proposal for ${selectedProposalLead.name}\n\nHi Team ${selectedProposalLead.name},\n\nI came across ${selectedProposalLead.name} on Google Maps in ${selectedProposalLead.location}. You have an impressive reputation with ${selectedProposalLead.rating}, but I noticed you currently do not have a dedicated online booking website.\n\nAt Mark Zap, we build modern, high-speed websites for local businesses.\n\nBest regards,\nMark Zap Digital Agency`);
                  alert('Proposal copied to clipboard!');
                }}
                style={{
                  backgroundColor: '#30D158',
                  color: '#000',
                  border: 'none',
                  borderRadius: '8px',
                  padding: '8px 18px',
                  fontWeight: 700,
                  fontSize: '13px',
                  cursor: 'pointer'
                }}
              >
                📋 Copy Proposal Text
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Docked Bottom Typing Bar */}
      <div 
        style={{
          position: 'fixed',
          bottom: '24px',
          left: '50%',
          transform: 'translateX(-50%)',
          width: 'calc(100% - 32px)',
          maxWidth: '728px',
          zIndex: 50,
          transition: 'transform 0.3s cubic-bezier(0.16, 1, 0.3, 1)'
        }}
      >
        <SearchInputBox 
          onSubmit={handleSendFollowUp} 
          placeholder="Search mid-range leads or upload PDF..." 
        />
      </div>
    </div>
  );
};
