import React, { useState, useEffect } from 'react';
import { jsPDF } from 'jspdf';
import { SearchInputBox } from './SearchInputBox';
import { useAuth } from '../AuthContext';
import { saveChatToSupabase } from '../chatService';
import { generateMarkZapAIResponse } from '../aiEngine';

export const ChatView = ({ initialQuery }) => {
  const { user } = useAuth();
  
  const initialAIResponse = generateMarkZapAIResponse(initialQuery || '');

  const [messages, setMessages] = useState([
    {
      id: 1,
      sender: 'user',
      text: initialQuery
    },
    {
      id: 2,
      sender: 'ai',
      text: initialQuery ? initialAIResponse.text : '',
      leads: initialAIResponse.leads
    }
  ]);

  const [approvedLeads, setApprovedLeads] = useState({});
  const [selectedProposalLead, setSelectedProposalLead] = useState(null);

  // Sync session to Supabase
  useEffect(() => {
    if (initialQuery && messages.length > 0) {
      saveChatToSupabase(user?.id, initialQuery, messages);
    }
  }, [messages, user, initialQuery]);

  const handleSendFollowUp = (queryText) => {
    if (!queryText.trim()) return;
    
    const aiResponse = generateMarkZapAIResponse(queryText);

    const userMsg = { id: Date.now(), sender: 'user', text: queryText };
    const aiMsg = {
      id: Date.now() + 1,
      sender: 'ai',
      text: aiResponse.text,
      leads: aiResponse.leads
    };
    setMessages((prev) => [...prev, userMsg, aiMsg]);
  };

  const handleApproveLead = (lead) => {
    setApprovedLeads((prev) => ({ ...prev, [lead.name]: true }));
    setSelectedProposalLead(lead);
  };

  /**
   * DIRECT 1-CLICK PDF FILE DOWNLOADER (Using jsPDF — No Print Dialogs!)
   */
  const handleDownloadPDF = (leadsList) => {
    if (!leadsList || leadsList.length === 0) return;

    const doc = new jsPDF({ unit: 'pt', format: 'a4' });

    // Document Header Title
    doc.setFillColor(14, 18, 16);
    doc.rect(0, 0, 595, 60, 'F');

    doc.setTextColor(48, 209, 88);
    doc.setFont('Helvetica', 'bold');
    doc.setFontSize(18);
    doc.text('Mark Zap Lead Intelligence Report', 30, 36);

    doc.setFontSize(9);
    doc.setTextColor(180, 180, 180);
    doc.text(`Generated by Agent-Reach Engine • Target: Businesses Without Websites • ${leadsList.length} Leads`, 305, 36, { align: 'right' });

    let yPos = 85;

    leadsList.forEach((lead, idx) => {
      // Check for page break
      if (yPos > 720) {
        doc.addPage();
        yPos = 50;
      }

      // Lead Card Box Frame
      doc.setFillColor(248, 249, 250);
      doc.setDrawColor(220, 220, 220);
      doc.roundedRect(30, yPos, 535, 125, 8, 8, 'FD');

      // Lead Title
      doc.setFont('Helvetica', 'bold');
      doc.setFontSize(13);
      doc.setTextColor(17, 17, 17);
      doc.text(`${idx + 1}. ${lead.name}`, 44, yPos + 22);

      // Status Badge
      doc.setFontSize(9);
      doc.setTextColor(220, 38, 38);
      doc.text(`${lead.websiteStatus}`, 550, yPos + 22, { align: 'right' });

      // Category & Location
      doc.setFont('Helvetica', 'normal');
      doc.setFontSize(9.5);
      doc.setTextColor(80, 80, 80);
      doc.text(`${lead.type} • ${lead.location}`, 44, yPos + 38);

      // Key Meta Grid
      doc.setFontSize(9);
      doc.setTextColor(30, 30, 30);
      doc.text(`Est. Revenue: ${lead.revenueEstimate}    |    Phone: ${lead.phone}    |    Email: ${lead.email}`, 44, yPos + 56);
      doc.text(`Rating: ${lead.rating}`, 44, yPos + 70);

      // Google Maps Link Text
      doc.setTextColor(10, 132, 255);
      doc.text(`Google Maps Link: ${lead.gmapsUrl}`, 44, yPos + 84);

      // Pitch Strategy Box
      doc.setFillColor(240, 253, 244);
      doc.setDrawColor(187, 247, 208);
      doc.roundedRect(44, yPos + 92, 507, 24, 4, 4, 'FD');

      doc.setFont('Helvetica', 'bold');
      doc.setFontSize(8.5);
      doc.setTextColor(22, 101, 52);
      const pitchText = `Why They Will Build: ${lead.whyBuildFromUs}`;
      const splitPitch = doc.splitTextToSize(pitchText, 495);
      doc.text(splitPitch[0], 52, yPos + 107);

      yPos += 138;
    });

    // Save as PDF file directly to downloads folder!
    const querySlug = (initialQuery || 'Leads').toLowerCase().replace(/[^a-z0-9]/g, '_');
    doc.save(`Mark_Zap_${querySlug}_Report.pdf`);
  };

  return (
    <div 
      style={{
        position: 'relative',
        zIndex: 20,
        width: '100%',
        maxWidth: '860px',
        margin: '0 auto',
        padding: '60px 20px 140px 20px',
        boxSizing: 'border-box',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        color: '#ffffff',
        fontFamily: "'Schibsted Grotesk', 'Inter', sans-serif"
      }}
    >
      {/* Messages Conversation Stream */}
      <div 
        style={{
          width: '100%',
          display: 'flex',
          flexDirection: 'column',
          gap: '24px'
        }}
      >
        {messages.map((msg) => {
          if (!msg.text) return null;

          if (msg.sender === 'user') {
            return (
              <div 
                key={msg.id}
                style={{
                  display: 'flex',
                  flexDirection: 'column',
                  alignItems: 'flex-end',
                  width: '100%'
                }}
              >
                <div 
                  style={{
                    fontSize: '12px',
                    fontWeight: 600,
                    color: 'rgba(255, 255, 255, 0.55)',
                    marginBottom: '6px',
                    paddingRight: '4px'
                  }}
                >
                  You
                </div>

                <div 
                  style={{
                    maxWidth: '85%',
                    padding: '16px 22px',
                    borderRadius: '18px 18px 4px 18px',
                    backgroundColor: 'rgba(255, 255, 255, 0.95)',
                    color: '#000000',
                    boxShadow: '0 10px 30px rgba(0, 0, 0, 0.25)',
                    fontSize: '16px',
                    lineHeight: '1.5',
                    fontWeight: 400
                  }}
                >
                  <p style={{ margin: 0 }}>{msg.text}</p>
                </div>
              </div>
            );
          }

          /* AI Response */
          return (
            <div 
              key={msg.id}
              style={{
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'flex-start',
                width: '100%',
                marginTop: '4px'
              }}
            >
              {/* AI Sender Label & Direct PDF Download Button */}
              <div 
                style={{
                  width: '100%',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'space-between',
                  marginBottom: '8px',
                  paddingLeft: '4px',
                  paddingRight: '4px'
                }}
              >
                <div style={{ fontSize: '12px', fontWeight: 600, color: 'rgba(255, 255, 255, 0.55)' }}>
                  Mark Zap Agent-Reach AI Engine
                </div>

                {msg.leads && msg.leads.length > 0 && (
                  <button
                    onClick={() => handleDownloadPDF(msg.leads)}
                    style={{
                      backgroundColor: '#30D158',
                      color: '#000000',
                      border: 'none',
                      borderRadius: '8px',
                      padding: '6px 14px',
                      fontSize: '12px',
                      fontWeight: 700,
                      cursor: 'pointer',
                      display: 'flex',
                      alignItems: 'center',
                      gap: '6px',
                      boxShadow: '0 4px 14px rgba(48, 209, 88, 0.3)',
                      transition: 'transform 0.15s ease'
                    }}
                  >
                    <span>⬇️ Download PDF File</span>
                  </button>
                )}
              </div>

              {/* AI Response Text */}
              <div 
                style={{
                  width: '100%',
                  color: '#ffffff',
                  fontSize: '15px',
                  lineHeight: '1.6',
                  fontWeight: 400,
                  paddingLeft: '4px',
                  whiteSpace: 'pre-wrap'
                }}
              >
                {msg.text}
              </div>

              {/* Agent-Reach Interactive Prospect Lead Cards */}
              {msg.leads && msg.leads.length > 0 && (
                <div style={{ width: '100%', display: 'flex', flexDirection: 'column', gap: '14px', marginTop: '16px' }}>
                  {msg.leads.map((lead, lIdx) => {
                    const isApproved = approvedLeads[lead.name];

                    return (
                      <div
                        key={lIdx}
                        style={{
                          backgroundColor: 'rgba(14, 18, 16, 0.95)',
                          border: isApproved ? '1px solid #30D158' : '1px solid rgba(255, 255, 255, 0.14)',
                          borderRadius: '16px',
                          padding: '18px 20px',
                          display: 'flex',
                          flexDirection: 'column',
                          gap: '10px',
                          boxShadow: '0 10px 30px rgba(0, 0, 0, 0.4)',
                          position: 'relative'
                        }}
                      >
                        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                          <div>
                            <div style={{ fontSize: '17px', fontWeight: 700, color: '#ffffff' }}>{lead.name}</div>
                            <div style={{ fontSize: '12.5px', color: 'rgba(255, 255, 255, 0.6)', marginTop: '2px' }}>
                              {lead.type} • {lead.location}
                            </div>
                          </div>
                          <span style={{ fontSize: '11.5px', fontWeight: 700, color: '#ff453a', backgroundColor: 'rgba(255, 69, 58, 0.15)', padding: '4px 10px', borderRadius: '8px' }}>
                            {lead.websiteStatus}
                          </span>
                        </div>

                        <div style={{ display: 'flex', flexWrap: 'wrap', gap: '16px', fontSize: '13px', color: 'rgba(255, 255, 255, 0.85)', paddingTop: '4px', borderTop: '1px solid rgba(255,255,255,0.06)' }}>
                          <div><strong>Est. Revenue:</strong> <span style={{ color: '#30D158' }}>{lead.revenueEstimate}</span></div>
                          <div><strong>Phone:</strong> <a href={`tel:${lead.phone}`} target="_blank" rel="noopener noreferrer" style={{ color: '#30D158', textDecoration: 'none' }}>{lead.phone}</a></div>
                          <div><strong>Email:</strong> <a href={`mailto:${lead.email}`} target="_blank" rel="noopener noreferrer" style={{ color: '#0A84FF', textDecoration: 'none' }}>{lead.email}</a></div>
                          <div><strong>Rating:</strong> {lead.rating}</div>
                        </div>

                        <div style={{ fontSize: '12.5px', color: 'rgba(255, 255, 255, 0.65)' }}>
                          <strong>Social Profiles:</strong> {lead.social}
                        </div>

                        {/* Why They Will Build From Us Callout Box */}
                        {lead.whyBuildFromUs && (
                          <div
                            style={{
                              backgroundColor: 'rgba(48, 209, 88, 0.10)',
                              border: '1px solid rgba(48, 209, 88, 0.25)',
                              borderRadius: '10px',
                              padding: '10px 14px',
                              fontSize: '12.5px',
                              color: '#ffffff',
                              lineHeight: '1.45'
                            }}
                          >
                            <strong style={{ color: '#30D158' }}>💡 Why They Will Build From Us:</strong> {lead.whyBuildFromUs}
                          </div>
                        )}

                        {/* Action Buttons: Open Maps & Approve Proposal */}
                        <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginTop: '4px' }}>
                          <a
                            href={lead.gmapsUrl}
                            target="_blank"
                            rel="noopener noreferrer"
                            style={{
                              backgroundColor: 'rgba(10, 132, 255, 0.18)',
                              color: '#0A84FF',
                              border: '1px solid rgba(10, 132, 255, 0.3)',
                              borderRadius: '8px',
                              padding: '6px 14px',
                              fontSize: '12.5px',
                              fontWeight: 600,
                              textDecoration: 'none',
                              display: 'inline-flex',
                              alignItems: 'center',
                              gap: '6px'
                            }}
                          >
                            📍 Open in Google Maps
                          </a>

                          <button
                            onClick={() => handleApproveLead(lead)}
                            style={{
                              backgroundColor: isApproved ? '#30D158' : 'rgba(48, 209, 88, 0.2)',
                              color: isApproved ? '#000000' : '#30D158',
                              border: '1px solid rgba(48, 209, 88, 0.4)',
                              borderRadius: '8px',
                              padding: '6px 14px',
                              fontSize: '12.5px',
                              fontWeight: 700,
                              cursor: 'pointer'
                            }}
                          >
                            {isApproved ? '✓ Approved — Proposal Ready' : '✅ Approve & Generate Proposal'}
                          </button>
                        </div>
                      </div>
                    );
                  })}
                </div>
              )}
            </div>
          );
        })}
      </div>

      {/* Modal Popup for Generated Proposal Email */}
      {selectedProposalLead && (
        <div
          style={{
            position: 'fixed',
            inset: 0,
            backgroundColor: 'rgba(0,0,0,0.85)',
            zIndex: 120,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            padding: '20px'
          }}
        >
          <div
            style={{
              width: '100%',
              maxWidth: '680px',
              backgroundColor: '#0c100e',
              border: '1px solid rgba(255, 255, 255, 0.16)',
              borderRadius: '24px',
              padding: '24px 28px',
              boxSizing: 'border-box',
              color: '#ffffff',
              boxShadow: '0 40px 100px rgba(0,0,0,0.9)'
            }}
          >
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
              <div style={{ fontSize: '18px', fontWeight: 700, color: '#30D158' }}>
                ✉️ Custom Sales Proposal & Cold Outreach Email
              </div>
              <button 
                onClick={() => setSelectedProposalLead(null)}
                style={{ background: 'none', border: 'none', color: '#fff', fontSize: '18px', cursor: 'pointer' }}
              >
                ✕
              </button>
            </div>

            <div style={{ fontSize: '13px', color: 'rgba(255,255,255,0.7)', marginBottom: '14px' }}>
              Target: <strong>{selectedProposalLead.name}</strong> ({selectedProposalLead.email})
            </div>

            <div
              style={{
                backgroundColor: '#070907',
                border: '1px solid rgba(255,255,255,0.1)',
                borderRadius: '12px',
                padding: '18px',
                fontSize: '13.5px',
                lineHeight: '1.6',
                fontFamily: 'monospace',
                whiteSpace: 'pre-wrap',
                color: '#d4d4d4'
              }}
            >
{`Subject: High-converting website proposal for ${selectedProposalLead.name}

Hi Team ${selectedProposalLead.name},

I came across ${selectedProposalLead.name} on Google Maps in ${selectedProposalLead.location}. You have an impressive reputation with ${selectedProposalLead.rating}, but I noticed you currently do not have a dedicated online booking website.

At Mark Zap, we build modern, high-speed websites for local businesses. Based on your location and lead volume, a custom website with online appointment booking can capture an estimated 30+ new customer bookings every week.

Would you be open to a 5-minute preview of a custom website design concept we prepared for ${selectedProposalLead.name}?

Best regards,
Mark Zap Digital Agency
Phone: ${selectedProposalLead.phone}`}
            </div>

            <div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: '18px', gap: '12px' }}>
              <button
                onClick={() => {
                  navigator.clipboard.writeText(`Subject: High-converting website proposal for ${selectedProposalLead.name}\n\nHi Team ${selectedProposalLead.name},\n\nI came across ${selectedProposalLead.name} on Google Maps in ${selectedProposalLead.location}. You have an impressive reputation with ${selectedProposalLead.rating}, but I noticed you currently do not have a dedicated online booking website.\n\nAt Mark Zap, we build modern, high-speed websites for local businesses.\n\nBest regards,\nMark Zap Digital Agency`);
                  alert('Proposal copied to clipboard!');
                }}
                style={{
                  backgroundColor: '#30D158',
                  color: '#000',
                  border: 'none',
                  borderRadius: '8px',
                  padding: '8px 18px',
                  fontWeight: 700,
                  fontSize: '13px',
                  cursor: 'pointer'
                }}
              >
                📋 Copy Proposal Text
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Docked Bottom Typing Bar */}
      <div 
        style={{
          position: 'fixed',
          bottom: '24px',
          left: '50%',
          transform: 'translateX(-50%)',
          width: 'calc(100% - 32px)',
          maxWidth: '728px',
          zIndex: 50,
          transition: 'transform 0.3s cubic-bezier(0.16, 1, 0.3, 1)'
        }}
      >
        <SearchInputBox 
          onSubmit={handleSendFollowUp} 
          placeholder="Search mid-range leads or upload PDF..." 
        />
      </div>
    </div>
  );
};
